# Generated by Django 5.0 on 2023-12-13 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('precio', models.FloatField(blank=True, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('potencia', models.CharField(blank=True, max_length=100, null=True)),
                ('motor', models.CharField(blank=True, max_length=200, null=True)),
                ('caracteristicas', models.TextField(blank=True, null=True)),
                ('capacidad', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo', models.CharField(choices=[('Automovil', 'Automovil'), ('Campero', 'Campero'), ('Camioneta', 'Camioneta'), ('Microbus', 'Microbus'), ('Buseta', 'Buseta'), ('Bus', 'Bus'), ('Camion', 'Camion'), ('Tracto camion', 'Tracto camion')], default='Automovil', max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes/vehiculos/')),
            ],
            options={
                'verbose_name_plural': 'Vehiculos',
                'ordering': ['numero_serie'],
            },
        ),
    ]
