# Generated by Django 5.0 on 2023-12-13 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orden_de_trabajo', '0001_initial'),
        ('repuesto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CotizacionOrdenDeTrabajo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('costo_reparacion', models.FloatField()),
                ('fecha_vencimiento', models.DateField()),
                ('habilitado', models.BooleanField(default=True)),
                ('orden_de_trabajo', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='cotizacion', to='orden_de_trabajo.ordendetrabajo')),
            ],
            options={
                'verbose_name_plural': 'Cotizaciones Ordenes de Trabajo',
                'ordering': ['fecha_vencimiento'],
            },
        ),
        migrations.CreateModel(
            name='RepuestoCantidad',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('cotizacion_orden_de_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repuestos_cantidad', to='cotizacion_orden_de_trabajo.cotizacionordendetrabajo')),
                ('repuesto', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='repuesto.repuesto')),
            ],
            options={
                'verbose_name_plural': 'Repuestos Cantidad',
                'unique_together': {('cotizacion_orden_de_trabajo', 'repuesto')},
            },
        ),
    ]
