# Generated by Django 5.0 on 2023-12-13 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        ('empleado', '0001_initial'),
        ('sucursal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_venta', models.DateField(auto_now_add=True)),
                ('precio_venta', models.FloatField()),
                ('forma_pago', models.CharField(choices=[('Credito', 'Credito'), ('Efectivo', 'Efectivo'), ('Tarjeta_credito', 'Tarjeta de credito'), ('Tarjeta_debito', 'Tarjeta de debito')], default='Efectivo', max_length=20)),
                ('habilitado', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='empleado.empleado')),
                ('sucursal_vehiculo', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='sucursal.sucursalvehiculo')),
            ],
            options={
                'verbose_name_plural': 'Ventas',
                'ordering': ['fecha_venta'],
            },
        ),
    ]
