# Generated by Django 5.0 on 2023-12-13 05:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        ('empleado', '0001_initial'),
        ('sucursal', '0001_initial'),
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenDeTrabajo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator('^[A-Z]{3}-[0-9]{3}', code='Invalid Key', message='Debe ingresar una placa valida ej: ABC-123')])),
                ('fecha_entrada', models.DateField(auto_now_add=True, null=True)),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('estado_reparacion', models.TextField(blank=True, choices=[('Pendiente', 'Pendiente'), ('Cotizado', 'Cotizado'), ('Reparado', 'Reparado'), ('Reparado y entregado', 'Reparado y entregado'), ('Retirado', 'Retirado')], default='Pendiente', max_length=50, null=True)),
                ('observacion', models.TextField(blank=True, max_length=200, null=True)),
                ('habilitado', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
                ('empleado', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='empleado.empleado')),
                ('sucursal', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sucursal.sucursal')),
                ('vehiculo', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='vehiculo.vehiculo')),
            ],
            options={
                'verbose_name_plural': 'Orden de Trabajo',
                'ordering': ['fecha_entrada'],
                'unique_together': {('placa', 'fecha_salida')},
            },
        ),
    ]
