# Generated by Django 5.0 on 2023-12-13 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('precio', models.FloatField(blank=True, null=True)),
                ('marca', models.CharField(blank=True, max_length=20, null=True)),
                ('clasificacion', models.CharField(blank=True, choices=[('Automotriz', 'Automotriz'), ('Ferreteria', 'Ferreteria'), ('Pinturas', 'Pinturas'), ('Rodamientos', 'Rodamientos'), ('Solventes', 'Solventes'), ('Bandas_cadenas', 'Bandas y cadenas'), ('Limpieza', 'Limpieza'), ('Autopartes', 'Autopartes'), ('Sellos_empaques', 'Sellos y empaques'), ('Lubricantes', 'Lubricantes')], default='Sellos_empaques', max_length=20, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes/repuestos/')),
                ('proveedor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='proveedor.proveedor')),
            ],
            options={
                'verbose_name_plural': 'Repuestos',
                'ordering': ['nombre'],
                'unique_together': {('nombre', 'proveedor')},
            },
        ),
    ]
